model_list:
  - model_name: instant
    litellm_params:
      model: "deeperseeker/deepseek-v4-flash"
  - model_name: vision
    litellm_params:
      model: "deeperseeker/deepseek-v4-vision"
  - model_name: expert
    litellm_params:
      model: "deeperseeker/deepseek-v4-pro"

litellm_settings:
  custom_provider_map:
    - provider: "deeperseeker"
      custom_handler: "deeperseeker_plugin.deeperseeker_instance"

general_settings:
  master_key: "dkseeker"
  ui_username: "admin"
  database_url: "postgresql://postgres:@/postgres?host=litellm_db"
