model_list:
  - model_name: instant
    litellm_params:
      model: "instant"
  - model_name: vision
    litellm_params:
      model: "vision"
  - model_name: expert
    litellm_params:
      model: "expert"

litellm_settings:
  custom_provider_map:
    - provider: "deeperseeker"
      custom_handler: "deeperseeker_plugin.deeperseeker_instance"

users:
  - user_id: "admin"
    role: "proxy_admin"
  - user_id: "default_user_id"
    role: "proxy_admin"

files_settings:
  - custom_llm_provider: "openai"
    api_key: "none"
    api_base: "http://localhost:4000/customfiles"

general_settings:
  pass_through_endpoints:
    - path: "/v1/files/<path>/content"
      target: "http://localhost:4000/v1/files/<path>/content"
