services:
  deeperseeker:
    build: .
    container_name: deeperseeker
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./deeperseeker.db
        target: /app/deeperseeker.db
        bind:
          create_host_path: false
      - type: bind
        source: ./aws_cookies_deepseek.json
        target: /app/aws_cookies_deepseek.json
        bind:
          create_host_path: false
    restart: unless-stopped
